version: '3.8'

name: admin_origami

services:
  admin_origami_web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: admin_origami_web
    restart: unless-stopped
    ports:
      - "8085:80"
    networks:
      - nginx_proxy_network

networks:
  nginx_proxy_network:
    external: true